# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:

tasks:
  init:
    desc: Initialize the solution (use on a fresh checkout)
    cmds:
      - dotnet tool restore

  publish:
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - dotnet test --no-build --configuration Release --verbosity normal
    - dotnet pack --no-build --configuration Release --output ${{ env.NuGetDirectory }}

  test:
    desc: Test the solution and generate a report
    cmds:
      - dotnet test
          --coverage
          --coverage-output-format cobertura
          --coverage-output coverage.cobertura.xml
      - dotnet reportgenerator
          -reports:tests/**/TestResults/coverage.cobertura.xml
          -targetdir:CoverageReport